# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 768d9f967b425c2b339f0363e938e086d9336d72e74eca0c8ec12fdbd0486e384afee31b5163bbebc62d2e321dbb90c0f8fdb13efadc091851752e95b0c4dab9

test:
  secret_key_base: a55a90c6f3da84134b7d7e05990ceed4a58cc4f7fd50a87f4cf0acfd831e7961364d5061a54439a5b732dc9b54ca17fab1952fc373ebfcd48f2c5e4fe468e589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
